name: Build Developer Handbook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install pandoc
      run: |
        pip install --upgrade pandoc

    - name: Generate HTML from markdown
      run: |
        cd docs
        python -m pandoc $(cat pandoc_order.txt) metadata.yaml --include-before-body=version.md -s -o developer_handbook.html --toc --number-sections --wrap=none

    - name: Generate PDF from HTML
      run: |
        cd docs
        python -m pandoc developer_handbook.html -s --pdf-engine=xelatex -o developer_handbook.pdf

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: developer-handbook
        path: docs/developer_handbook.pdf