name: Build Developer Handbook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install pandoc
      run: |
        sudo apt-get install texlive-latex-base pandoc -y

    - name: Verify files
      run: |
        cd docs
        ls -la ./
        for file in $(cat pandoc_order.txt); do
          if [ ! -f "$file" ]; then
            echo "File $file not found!"
            exit 1
          fi
        done

    - name: Generate HTML from markdown
      run: |
        cd docs
        pandoc $(cat pandoc_order.txt) metadata.yaml --include-before-body=version.md -s -o developer_handbook.html --toc --number-sections --wrap=none

    - name: Generate PDF from HTML
      run: |
        cd docs
        pandoc developer_handbook.html -s --pdf-engine=pdflatex -o developer_handbook.pdf

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: developer-handbook
        path: docs/developer_handbook.pdf
